sudo: required
language: python
before_install:
 - sudo apt-get install -qq liblzma-dev
python:
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"
install:
 - pip install -r requirements.txt
 - make build
 - sudo make install
# command to run tests
script:
 - make test
